#cloud-config
cloud_config_modules:
  - resolv_conf
  - users_groups
  - package_update_upgrade_install
  - runcmd
manage_resolv_conf: true
resolv_conf:
  nameservers: ['8.8.4.4', '8.8.8.8']
  searchdomains:
    - moclocal
  domain:
    - moclocal
  options:
    rotate: true
    timeout: 1
package_upgrade: true
packages:
  - git
  - gcc
  - wget
  - vim
  - tmux
  - svn
package_reboot_if_required: true
users:
  - default
  - name: stack
    sudo: ALL=(ALL) NOPASSWD:ALL
    homedir: /opt/stack
    shell: /bin/bash
runcmd:
  - [su, -c, "git clone -b stable/pike https://github.com/openstack-dev/devstack.git /opt/stack/devstack", stack]
  - [su, -c, 'svn export --force https://github.com/CCI-MOC/ORE/trunk/patch /opt/stack/devstack/', stack]
  - 'sudo cp -r /home/centos/.ssh /opt/stack/'
  - 'sudo chown -R stack /opt/stack/.ssh'
  - 'sudo echo -e "if [[ \$- == *i* ]] && [ -d "/opt/stack/keystone" ]; then\n        . /opt/stack/devstack/openrc admin admin\nfi" >> /opt/stack/.bashrc'
